baseurl = "https://blog.jombangdigital.net"
title = "JD.net"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service 
    disable = false
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = false
    respectDoNotTrack = false
    useSessionStorage = false

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Eat Sleep Coding"
  description = "Microblog, Server Log, &amp; Notes" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Randhi P. Putra"
  authorLink = "https://jombangdigital.net/"
  bio = [
    "Randhi is a full-stack developper, mostly use Laravel and also known as the founder of <a href='https://jombangdigital.net/'>Primera Sistem Nusantara</a>."
  ]
  copyright = [
    "&copy; 2018 Randhi P. Putra",
    "Hugo Theme by [Appernetic](https://appernetic.io).",
    "A port of Tracks by Compete Themes."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "randhi.pp@gmail.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
	email		  = "mailto:randhi.pp@gmail.com"
	twitter       = "https://twitter.com/ranrandhi"
    instagram     = "https://instagram.com/randhipp"
    github        = "https://github.com/randhipp"
	rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Randhi P. Putra"
  [params.writers]
    

    [params.writers."Randhi P. Putra"]
    link = "https://jombangdigital.net/"
    email = "randhi.pp@gmail.com"
    bio = [
      "Randhi is a full-stack developper, mostly use Laravel and also known as the founder of <a href='https://jombangdigital.net/'>Primera Sistem Nusantara</a>."
    ]
 #  facebook      = "https://facebook.com/randhi.pp"
 #   googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/ranrandhi"
 #   linkedin      = "full profile url in linkedin"
 #  stackoverflow = "full profile url in stackoverflow"
    instagram     = "https://instagram.com/randhipp"
    github        = "https://github.com/randhipp"
 #   pinterest     = "full profile url in pinterest"
